/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.KeyStroke;

/**
 *
 * @author david
 */
public class PanelMensaje extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private static String mensaje;
    private static int tipo;
    private int resultadoOpcion = -1;
    private String nombre;

    public String getNombre() {
        return nombre;
    }

    public int getResultado() {
        return resultadoOpcion;
    }

    public void setLblIconoImput(ImageIcon icon) {
        this.lblIconoImput.setIcon(icon);
    }

    /**
     * Creates new form PanelMensaje
     */
    public PanelMensaje(java.awt.Frame parent, boolean modal, String texto, int tipo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.tipo = tipo;
        this.nombre = "";
        this.mensaje = texto;
        if (tipo == 1) {
            this.lblIconoImput.setVisible(false);
            this.lblIconoNivel.setVisible(false);
            this.lblSubirNivel.setVisible(false);
            this.lblImput.setVisible(false);
            this.txtMascota.setVisible(false);
            this.lblMensajeSyN.setVisible(true);
            this.lblMensajeSyN.setText(mensaje);
        } else if (tipo == 2) {
            this.lblIconoImput.setVisible(true);
            this.lblImput.setVisible(true);
            this.txtMascota.setVisible(true);
            this.lblMensajeSyN.setVisible(false);
            this.lblIconoNivel.setVisible(false);
            this.lblSubirNivel.setVisible(false);
        } else if (tipo == 3) {
            this.lblIconoImput.setVisible(false);
            this.lblImput.setVisible(false);
            this.txtMascota.setVisible(false);
            this.lblIconoNivel.setVisible(false);
            this.lblSubirNivel.setVisible(false);
            this.lblMensajeSyN.setVisible(true);
            this.lblMensajeSyN.setText(mensaje);
            this.btnNo.setVisible(false);
        } else if (tipo == 4) {
            this.lblIconoImput.setVisible(false);
            this.lblImput.setVisible(false);
            this.txtMascota.setVisible(false);
            this.lblIconoNivel.setVisible(true);
            this.lblSubirNivel.setVisible(true);
            this.lblMensajeSyN.setVisible(false);
            this.lblSubirNivel.setText(mensaje);
            this.btnNo.setVisible(false);
        }

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        txtMascota = new javax.swing.JTextField();
        lblIconoNivel = new javax.swing.JLabel();
        lblSubirNivel = new javax.swing.JLabel();
        lblIconoImput = new javax.swing.JLabel();
        lblImput = new javax.swing.JLabel();
        lblMensajeSyN = new javax.swing.JLabel();
        lblFondoMensaje = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/comprobado_Apagado.png"))); // NOI18N
        okButton.setContentAreaFilled(false);
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/comprobado_Grande.png"))); // NOI18N
        okButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/comprobado.png"))); // NOI18N
        okButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        okButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 50, 50));
        getRootPane().setDefaultButton(okButton);

        btnNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/cancelar_Apagado.png"))); // NOI18N
        btnNo.setContentAreaFilled(false);
        btnNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/cancelar_Grande.png"))); // NOI18N
        btnNo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/cancelar.png"))); // NOI18N
        btnNo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 50));

        txtMascota.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        txtMascota.setForeground(new java.awt.Color(102, 102, 102));
        txtMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMascotaActionPerformed(evt);
            }
        });
        txtMascota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMascotaKeyPressed(evt);
            }
        });
        getContentPane().add(txtMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, -1));

        lblIconoNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/elevar-a-mismo-nivel.png"))); // NOI18N
        getContentPane().add(lblIconoNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 70));

        lblSubirNivel.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        lblSubirNivel.setForeground(new java.awt.Color(102, 102, 102));
        lblSubirNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblSubirNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, 70));

        lblIconoImput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/iconoInput.gif"))); // NOI18N
        getContentPane().add(lblIconoImput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 70));

        lblImput.setForeground(new java.awt.Color(255, 255, 255));
        lblImput.setText("INGRESE NOMBRE DE MASCOTA:");
        getContentPane().add(lblImput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        lblMensajeSyN.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        lblMensajeSyN.setForeground(new java.awt.Color(102, 102, 102));
        lblMensajeSyN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMensajeSyN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 110));

        lblFondoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/fondoMensajes.jpg"))); // NOI18N
        getContentPane().add(lblFondoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (tipo == 1) {
            this.resultadoOpcion = 0;
        } else if (tipo == 2) {
            this.nombre = this.txtMascota.getText();
        }
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        doClose(RET_CANCEL);
        this.resultadoOpcion = 1;
    }//GEN-LAST:event_btnNoActionPerformed

    private void txtMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMascotaActionPerformed

    private void txtMascotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMascotaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.nombre = this.txtMascota.getText();
            doClose(RET_OK);
        }
    }//GEN-LAST:event_txtMascotaKeyPressed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelMensaje dialog = new PanelMensaje(new javax.swing.JFrame(), true, mensaje, tipo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JLabel lblFondoMensaje;
    private javax.swing.JLabel lblIconoImput;
    private javax.swing.JLabel lblIconoNivel;
    private javax.swing.JLabel lblImput;
    private javax.swing.JLabel lblMensajeSyN;
    private javax.swing.JLabel lblSubirNivel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField txtMascota;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
