/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Objetos.Mascota;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author david
 */
public class Pantalla_Cocina extends javax.swing.JPanel {

    private Pantalla_Juego juego;
    private boolean estaComiendo;

    /**
     * Creates new form Pantalla_Cocina
     */
    public Pantalla_Cocina(Pantalla_Juego j) {
        initComponents();
        this.juego = j;
        this.llenarProductos();
        this.pFondoComida.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComer = new javax.swing.JButton();
        pFondoComida = new javax.swing.JPanel();
        btnSuero = new javax.swing.JButton();
        lblcantSuero = new javax.swing.JLabel();
        btnPastilla = new javax.swing.JButton();
        lblcantPastilla = new javax.swing.JLabel();
        btnJarabe = new javax.swing.JButton();
        lblcantJarabe = new javax.swing.JLabel();
        btnPizza = new javax.swing.JButton();
        lblcantPizza = new javax.swing.JLabel();
        btnHamburguesa = new javax.swing.JButton();
        lblcantHamburguesa = new javax.swing.JLabel();
        btnSushi = new javax.swing.JButton();
        lblcantSushi = new javax.swing.JLabel();
        lblPerrito = new javax.swing.JLabel();
        lblFondoCocina = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComer.setBackground(new java.awt.Color(51, 51, 51));
        btnComer.setFont(new java.awt.Font("HP Simplified Hans", 1, 18)); // NOI18N
        btnComer.setForeground(new java.awt.Color(51, 51, 51));
        btnComer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/tenedor_Apagado.png"))); // NOI18N
        btnComer.setText("COMER");
        btnComer.setContentAreaFilled(false);
        btnComer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/tenedor_Grande.png"))); // NOI18N
        btnComer.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/tenedor.png"))); // NOI18N
        btnComer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnComer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComerMouseExited(evt);
            }
        });
        btnComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComerActionPerformed(evt);
            }
        });
        add(btnComer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 110, 80));

        pFondoComida.setBackground(new java.awt.Color(102, 102, 102));
        pFondoComida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pFondoComida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/suero.png"))); // NOI18N
        btnSuero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSueroActionPerformed(evt);
            }
        });
        pFondoComida.add(btnSuero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, 50));

        lblcantSuero.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblcantSuero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantSuero.setText("0");
        lblcantSuero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFondoComida.add(lblcantSuero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, -1));

        btnPastilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/medicamento.png"))); // NOI18N
        btnPastilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPastilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastillaActionPerformed(evt);
            }
        });
        pFondoComida.add(btnPastilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 50));

        lblcantPastilla.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblcantPastilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantPastilla.setText("0");
        lblcantPastilla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFondoComida.add(lblcantPastilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, -1));

        btnJarabe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/jarabe.png"))); // NOI18N
        btnJarabe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJarabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJarabeActionPerformed(evt);
            }
        });
        pFondoComida.add(btnJarabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, 50));

        lblcantJarabe.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblcantJarabe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantJarabe.setText("0");
        lblcantJarabe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFondoComida.add(lblcantJarabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, -1));

        btnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/porcion-de-pizza.png"))); // NOI18N
        btnPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaActionPerformed(evt);
            }
        });
        pFondoComida.add(btnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        lblcantPizza.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblcantPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantPizza.setText("0");
        lblcantPizza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFondoComida.add(lblcantPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        btnHamburguesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/hamburguesa-con-queso.png"))); // NOI18N
        btnHamburguesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaActionPerformed(evt);
            }
        });
        pFondoComida.add(btnHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 50));

        lblcantHamburguesa.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblcantHamburguesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantHamburguesa.setText("0");
        lblcantHamburguesa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFondoComida.add(lblcantHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, -1));

        btnSushi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/sushi.png"))); // NOI18N
        btnSushi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSushiActionPerformed(evt);
            }
        });
        pFondoComida.add(btnSushi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        lblcantSushi.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblcantSushi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantSushi.setText("0");
        lblcantSushi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFondoComida.add(lblcantSushi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 50, -1));

        add(pFondoComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 160));

        lblPerrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/perritoPastorAleman.gif"))); // NOI18N
        add(lblPerrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 200));

        lblFondoCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/fondoCocina.jpg"))); // NOI18N
        add(lblFondoCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 460, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComerActionPerformed
        if (this.pFondoComida.isVisible()) {
            this.pFondoComida.setVisible(false);
        } else {
            this.pFondoComida.setVisible(true);
        }
    }//GEN-LAST:event_btnComerActionPerformed
    private boolean comer(int cantComida) {
        if (juego.getMascota().getHambre() >= 99) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>TU MASCOTA ESTA <br> SATISFECHA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "Tu mascota ya esta satisfecha");
            return false;
        } else {
            int valor = juego.getMascota().getHambre() + cantComida;
            juego.getPbHambre().setValue(valor);
            juego.getMascota().setHambre(valor);
            this.lblPerrito.setIcon(new ImageIcon("src/Elementos_Graficos/perrito comiendo.gif"));
            return true;
        }
    }

    private boolean curar(int cantCura) {
        if (juego.getMascota().getVida() >= 99) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>TU MASCOTA TIENE <br> SU SALUD AL MAXIMO</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "Tu mascota tiene su salud al maximo");
            return false;
        } else {
            int valor = juego.getMascota().getVida() + cantCura;
            juego.getPbVida().setValue(valor);
            juego.getMascota().setVida(valor);
            this.lblPerrito.setIcon(new ImageIcon("src/Elementos_Graficos/perrito comiendo.gif"));
            return true;
        }
    }
    private void btnComerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComerMouseEntered
        this.btnComer.setForeground(Color.white);
    }//GEN-LAST:event_btnComerMouseEntered

    private void btnComerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComerMouseExited
        this.btnComer.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnComerMouseExited

    private void btnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaActionPerformed
        int cantPizzas = Integer.valueOf(this.lblcantPizza.getText());
        if (cantPizzas == 0) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>NO TIENES ESTE PRODUCTO<br> COMPRALO EN LA TIENDA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "No tienes este producto compralo en la tienda");
        } else {
            boolean siComio = this.comer(5);
            if (siComio) {
                this.juego.getMascota().setCantPizzas(juego.getMascota().getCantPizzas() - 1);
                this.lblcantPizza.setText(String.valueOf(cantPizzas - 1));
                this.juego.incrementarExperiencia(4);
            }
        }
    }//GEN-LAST:event_btnPizzaActionPerformed

    private void btnHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaActionPerformed
        int cantHamburguesa = Integer.valueOf(this.lblcantHamburguesa.getText());
        if (cantHamburguesa == 0) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>NO TIENES ESTE PRODUCTO<br> COMPRALO EN LA TIENDA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "No tienes este producto compralo en la tienda");
        } else {
            boolean siComio = this.comer(15);
            if (siComio) {
                juego.getMascota().setCantHamburguesas(juego.getMascota().getCantHamburguesas() - 1);
                this.lblcantHamburguesa.setText(String.valueOf(cantHamburguesa - 1));
                this.juego.incrementarExperiencia(6);
            }
        }
    }//GEN-LAST:event_btnHamburguesaActionPerformed

    private void btnSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSushiActionPerformed
        int cantSushi = Integer.valueOf(this.lblcantSushi.getText());
        if (cantSushi == 0) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>NO TIENES ESTE PRODUCTO<br> COMPRALO EN LA TIENDA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "No tienes este producto compralo en la tienda");
        } else {
            boolean siComio = this.comer(25);
            if (siComio) {
                juego.getMascota().setCantSushis(juego.getMascota().getCantSushis() - 1);
                this.lblcantSushi.setText(String.valueOf(cantSushi - 1));
                this.juego.incrementarExperiencia(12);
            }
        }
    }//GEN-LAST:event_btnSushiActionPerformed

    private void btnPastillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastillaActionPerformed
        int cantPastillas = Integer.valueOf(this.lblcantPastilla.getText());
        if (cantPastillas == 0) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>NO TIENES ESTE PRODUCTO<br> COMPRALO EN LA TIENDA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "No tienes este producto compralo en la tienda");
        } else {
            boolean siCuro = this.curar(5);
            if (siCuro) {
                juego.getMascota().setCantPastillas(juego.getMascota().getCantPastillas() - 1);
                this.lblcantPastilla.setText(String.valueOf(cantPastillas - 1));
                this.juego.incrementarExperiencia(7);
            }
        }
    }//GEN-LAST:event_btnPastillaActionPerformed

    private void btnJarabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJarabeActionPerformed
        int cantJarabes = Integer.valueOf(this.lblcantJarabe.getText());
        if (cantJarabes == 0) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>NO TIENES ESTE PRODUCTO<br> COMPRALO EN LA TIENDA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "No tienes este producto compralo en la tienda");
        } else {
            boolean siCuro = this.curar(15);
            if (siCuro) {
                juego.getMascota().setCantJarabes(juego.getMascota().getCantJarabes() - 1);
                this.lblcantJarabe.setText(String.valueOf(cantJarabes - 1));
                this.juego.incrementarExperiencia(10);
            }
        }
    }//GEN-LAST:event_btnJarabeActionPerformed

    private void btnSueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSueroActionPerformed
        int cantSueros = Integer.valueOf(this.lblcantSuero.getText());
        if (cantSueros == 0) {
            PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>NO TIENES ESTE PRODUCTO<br> COMPRALO EN LA TIENDA</html>", 3);
            pm.setVisible(true);
            //JOptionPane.showMessageDialog(this, "No tienes este producto compralo en la tienda");
        } else {
            boolean siCuro = this.curar(25);
            if (siCuro) {
                juego.getMascota().setCantSueros(juego.getMascota().getCantSueros() - 1);
                this.lblcantSuero.setText(String.valueOf(cantSueros - 1));
                this.juego.incrementarExperiencia(20);
            }
        }
    }//GEN-LAST:event_btnSueroActionPerformed

    public void llenarProductos() {
        int pizzas = this.juego.getMascota().getCantPizzas();
        int hamburguesas = this.juego.getMascota().getCantHamburguesas();
        int sushis = this.juego.getMascota().getCantSushis();
        int pastillas = this.juego.getMascota().getCantPastillas();
        int jarabes = this.juego.getMascota().getCantJarabes();
        int sueros = this.juego.getMascota().getCantSueros();
        this.lblcantPizza.setText(String.valueOf(pizzas));
        this.lblcantHamburguesa.setText(String.valueOf(hamburguesas));
        this.lblcantSushi.setText(String.valueOf(sushis));
        this.lblcantPastilla.setText(String.valueOf(pastillas));
        this.lblcantJarabe.setText(String.valueOf(jarabes));
        this.lblcantSuero.setText(String.valueOf(sueros));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComer;
    private javax.swing.JButton btnHamburguesa;
    private javax.swing.JButton btnJarabe;
    private javax.swing.JButton btnPastilla;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnSuero;
    private javax.swing.JButton btnSushi;
    private javax.swing.JLabel lblFondoCocina;
    private javax.swing.JLabel lblPerrito;
    private javax.swing.JLabel lblcantHamburguesa;
    private javax.swing.JLabel lblcantJarabe;
    private javax.swing.JLabel lblcantPastilla;
    private javax.swing.JLabel lblcantPizza;
    private javax.swing.JLabel lblcantSuero;
    private javax.swing.JLabel lblcantSushi;
    private javax.swing.JPanel pFondoComida;
    // End of variables declaration//GEN-END:variables
}
