/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import java.io.*;
import Objetos.Musica;
import Objetos.Partida;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author david
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    private Partida[] partidas = new Partida[3];
    private Musica mus;
    private Pantalla_Configuraciones conf;
    private boolean estado;

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public JPanel getjPanel1() {
        return this.jpPrincipal;
    }

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal(Musica m) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.mus = m;
        //this.conf = new Pantalla_Configuraciones(this, true);
        if (this.mus != null && this.estado) {
            this.mus.play();
        }
        this.setResizable(false);
    }

    public Musica getMus() {
        return this.mus;
    }

    public JPanel getJpPrincipal() {
        return jpPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpPrincipal = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnConfiguraciones = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("HP Simplified Hans Light", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/cerrar-sesion_Apagado.png"))); // NOI18N
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/cerrar-sesion_Grande.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/cerrar-sesion.png"))); // NOI18N
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpPrincipal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, 110));

        btnJugar.setFont(new java.awt.Font("HP Simplified Hans Light", 1, 14)); // NOI18N
        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/boton-de-play_apagado.png"))); // NOI18N
        btnJugar.setContentAreaFilled(false);
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/boton-de-play_Grande.png"))); // NOI18N
        btnJugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/boton-de-play.png"))); // NOI18N
        btnJugar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnJugar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jpPrincipal.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, 110));

        btnConfiguraciones.setFont(new java.awt.Font("HP Simplified Hans Light", 1, 14)); // NOI18N
        btnConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/configuraciones_Apagado.png"))); // NOI18N
        btnConfiguraciones.setContentAreaFilled(false);
        btnConfiguraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguraciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguraciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/configuraciones_Grande.png"))); // NOI18N
        btnConfiguraciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/configuraciones.png"))); // NOI18N
        btnConfiguraciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConfiguraciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionesActionPerformed(evt);
            }
        });
        jpPrincipal.add(btnConfiguraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 110, 110));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/Titulo Juego.png"))); // NOI18N
        jpPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 420, 150));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/fondoPrincipal.gif"))); // NOI18N
        jpPrincipal.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        getContentPane().add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        this.CambiarPanel(new SelectorPartida(this.obtenerPartidasDesdeArchivo(), this));
        //this.mus.stop();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionesActionPerformed
        this.conf = new Pantalla_Configuraciones(this, true);
        this.conf.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionesActionPerformed
    private void CambiarPanel(JPanel p) {
        //Metodo para cambiar y adaptar el fondo para la pantalla principal del menu
        p.setSize(590, 405);
        p.setLocation(0, 0);
        //this.mus.stop();
        this.jpPrincipal.removeAll();
        this.jpPrincipal.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        this.jpPrincipal.revalidate();
        this.jpPrincipal.repaint();
    }

    public void apagarMusica() {
        this.mus.stop();
        this.estado = false;
    }

    public void encenderMusica() {
        this.mus.play();
        this.estado = true;
    }

    public void cambairVolumenMusica(float vol) {
        this.mus.setVolume(vol);
    }
    
    public Partida[] obtenerPartidasDesdeArchivo() {
        List<Partida> partidas = new ArrayList<>();
        int lineaActual = 0; // Contador para mantener el seguimiento de la línea actual
        try (BufferedReader reader = new BufferedReader(new FileReader("src/Archivos/partidas.txt"))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                if (lineaActual > 0) { // Omitir la primera línea (encabezado)
                    String[] datos = linea.split(",");
                    if (datos.length == 2) {
                        String mascota = datos[0];
                        String estado = datos[1];
                        partidas.add(new Partida(mascota, estado));
                    }
                }
                lineaActual++;
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo de partidas: " + e.getMessage());
        }
        return partidas.toArray(new Partida[0]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Musica m = new Musica("src/Audios/musicaPrincipal.wav");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguraciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
