/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author david
 */
public class Pantalla_Muerte extends javax.swing.JPanel {

    /**
     * Creates new form Pantalla_Muerte
     */
    public Pantalla_Muerte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoPerrito = new javax.swing.JLabel();
        lblMensajeMuerte = new javax.swing.JLabel();
        lblFondoCielo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoPerrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/perritoEnCielo (1).gif"))); // NOI18N
        add(lblIconoPerrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 240, 250));

        lblMensajeMuerte.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        lblMensajeMuerte.setForeground(new java.awt.Color(0, 0, 0));
        lblMensajeMuerte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeMuerte.setText("¡TU MASCOTA MURIO!");
        add(lblMensajeMuerte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 450, 50));

        lblFondoCielo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/fondoCielo.gif"))); // NOI18N
        add(lblFondoCielo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFondoCielo;
    private javax.swing.JLabel lblIconoPerrito;
    private javax.swing.JLabel lblMensajeMuerte;
    // End of variables declaration//GEN-END:variables
}
