/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author david
 */
public class Pantalla_Cuarto extends javax.swing.JPanel {

    private Timer timer;
    private boolean estaDurmiendo = false;
    private Pantalla_Juego juego;
    private ImageIcon perritoDuerme = new ImageIcon("src/Elementos_Graficos/perrito durmiendo.gif");
    private ImageIcon perritoDespierta = new ImageIcon("src/Elementos_Graficos/perrito levantando.gif");
    private int nivelEnergia;

    public boolean isEstaDurmiendo() {
        return this.estaDurmiendo;
    }

    /**
     * Creates new form Pantalla_Cuarto
     */
    public Pantalla_Cuarto(Pantalla_Juego p) {
        initComponents();
        this.juego = p;
        this.timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (juego.getMascota().getEnergía() >= 99) {
                    detenerSueño();
                    juego.incrementarExperiencia(10);
                } else {
                    int valor = juego.getMascota().getEnergía() + 6;
                    juego.getPbEnergia().setValue(valor);
                    juego.getMascota().setEnergía(valor);
                }
            }
        ;
    }

    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLuz = new javax.swing.JButton();
        lblPerrito = new javax.swing.JLabel();
        lblFondoCuarto = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLuz.setForeground(new java.awt.Color(0, 0, 0));
        btnLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/foco_Prendido.png"))); // NOI18N
        btnLuz.setText("DORMIR");
        btnLuz.setContentAreaFilled(false);
        btnLuz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLuz.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLuz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuzActionPerformed(evt);
            }
        });
        add(btnLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 140, 90));

        lblPerrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/perritoPastorAleman.gif"))); // NOI18N
        add(lblPerrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 230, 270));

        lblFondoCuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/fondoCuarto_dia.png"))); // NOI18N
        add(lblFondoCuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 460, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuzActionPerformed

        String palabra = this.btnLuz.getText();
        if (palabra.equalsIgnoreCase("dormir")) {
            if (this.juego.getMascota().getEnergía() >= 90) {
                PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>TU MASCOTA TIENE SUFICIENTE <br> ENERGÍA</html>", 3);
                pm.setVisible(true);
                //JOptionPane.showMessageDialog(this, "Tu mascota tiene mucha energia como para dormir");
            } else {
                this.perritoDuerme.getImage().flush();
                this.btnLuz.setForeground(Color.white);
                this.btnLuz.setText("LEVANTAR");
                this.btnLuz.setIcon(new ImageIcon("src/Elementos_Graficos/foco_Apagado.png"));
                this.lblPerrito.setIcon(this.perritoDuerme);
                this.lblFondoCuarto.setIcon(new ImageIcon("src/Elementos_Graficos/fondoCuarto_noche.png"));
                timer.start();
                this.estaDurmiendo = true;
            }
        } else if (palabra.equalsIgnoreCase("levantar")) {
            detenerSueño();
        }
    }//GEN-LAST:event_btnLuzActionPerformed
    private void detenerSueño() {
        timer.stop();
        this.estaDurmiendo = false;
        this.perritoDespierta.getImage().flush();
        this.btnLuz.setForeground(Color.black);
        this.btnLuz.setText("DORMIR");
        this.btnLuz.setIcon(new ImageIcon("src/Elementos_Graficos/foco_Prendido.png"));
        this.lblPerrito.setIcon(this.perritoDespierta);
        this.lblFondoCuarto.setIcon(new ImageIcon("src/Elementos_Graficos/fondoCuarto_dia.png"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuz;
    private javax.swing.JLabel lblFondoCuarto;
    private javax.swing.JLabel lblPerrito;
    // End of variables declaration//GEN-END:variables
}
