/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author david
 */
public class Pantalla_Baño extends javax.swing.JPanel {

    private boolean estaBañando = false;
    private Timer timer;
    private Pantalla_Juego juego;

    public boolean isEstaBañandose() {
        return this.estaBañando;
    }

    /**
     * Creates new form Pantalla_Baño
     */
    public Pantalla_Baño(Pantalla_Juego juego) {
        initComponents();
        this.juego = juego;
        this.timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (juego.getMascota().getHigiene() >= 99) {
                    detenerBaño();
                } else {
                    int valor = juego.getMascota().getHigiene() + 6;
                    juego.getPbHigiene().setValue(valor);
                    juego.getMascota().setHigiene(valor);
                }
            }
        ;
    }

    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBañar = new javax.swing.JButton();
        lblPerrito = new javax.swing.JLabel();
        lblFondoBaño = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBañar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnBañar.setForeground(new java.awt.Color(51, 51, 51));
        btnBañar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/esponja_Apagada.png"))); // NOI18N
        btnBañar.setText("BAÑAR");
        btnBañar.setContentAreaFilled(false);
        btnBañar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBañar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBañar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/esponja_Grande.png"))); // NOI18N
        btnBañar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/esponja.png"))); // NOI18N
        btnBañar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBañar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBañar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBañarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBañarMouseExited(evt);
            }
        });
        btnBañar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBañarActionPerformed(evt);
            }
        });
        add(btnBañar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 90));

        lblPerrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/perritoPastorAleman.gif"))); // NOI18N
        add(lblPerrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 250));

        lblFondoBaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos_Graficos/fondoBaño.gif"))); // NOI18N
        add(lblFondoBaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 460, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBañarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBañarActionPerformed
        if (!estaBañando) {
            if (this.juego.getMascota().getHigiene() <= 90) {
                this.bañarMascota();
                this.estaBañando = true;
            } else {
                PanelMensaje pm = new PanelMensaje((JFrame) SwingUtilities.getWindowAncestor(this), true, "<html>TU MASCOTA ESTA LIMPIA <br> NO NECESITAS BAÑARLO</html>", 3);
                pm.setVisible(true);
                //JOptionPane.showMessageDialog(this, "Tu mascota esta limpia no necesitas bañarlo");
            }
        }
    }//GEN-LAST:event_btnBañarActionPerformed

    private void btnBañarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBañarMouseEntered
        this.btnBañar.setForeground(Color.white);
    }//GEN-LAST:event_btnBañarMouseEntered

    private void btnBañarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBañarMouseExited
        this.btnBañar.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnBañarMouseExited

    public void bañarMascota() {
        timer.start();
        this.lblPerrito.setIcon(new ImageIcon("src/Elementos_Graficos/perrito bañandose.gif"));
    }

    public void detenerBaño() {
        timer.stop();
        juego.incrementarExperiencia(6);
        this.lblPerrito.setIcon(new ImageIcon("src/Elementos_Graficos/perritoPastorAleman.gif"));
        estaBañando = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBañar;
    private javax.swing.JLabel lblFondoBaño;
    private javax.swing.JLabel lblPerrito;
    // End of variables declaration//GEN-END:variables
}
